### ISSUE TITLE
全体: Hydra設定ファイル構成の標準化

### ISSUE THREAD

**Issue by Motoki0705** [Motoki0705/Tennis-Analyzer#16]
### 概要
テニスアナライザーの各モジュール（ball, court, player, pose）のHydra設定ファイル構成をeventモジュールをベースに標準化する。

### 目的
- 一貫した設定ファイル構造で設定管理を統一
- 各モジュール間での設定ファイルの理解と操作を容易にする
- 再現性と実験追跡を向上させる

### チェックリスト
- [ ] 標準設定ファイル構造の定義
  ```
  configs/train/<module_name>/
  ├── config.yaml         # メイン設定ファイル
  ├── litmodule/          # LitModuleの設定
  │   └── <specific_model>.yaml
  ├── litdatamodule/      # DataModuleの設定
  │   └── <specific_data>.yaml
  ├── trainer/            # トレーナー設定
  │   └── default.yaml
  └── callbacks/          # コールバック設定
      └── default.yaml
  ```
- [ ] メイン設定ファイル（config.yaml）のテンプレート作成
  ```yaml
  # @package _global_
  
  # hydra設定
  hydra:
    output_subdir: hydra_outputs/${now:%Y-%m-%d_%H-%M-%S}
    run:
      dir: outputs/<module_name>/${version}/${now:%Y-%m-%d_%H-%M-%S}
  
  # デフォルト設定
  defaults:
    - litmodule: <default_lit_module>
    - litdatamodule: <default_data_module>
    - trainer: default
    - callbacks: default
    - _self_
  
  # 再現性のための乱数シード
  seed: 42
  
  # 実験名の設定
  version: ${litmodule.meta.name}_${litdatamodule.dataset_type}
  ```
- [ ] 各モジュール（ball, court, player, pose）の設定ファイル構造を確認
- [ ] 必要なディレクトリの作成
- [ ] 標準テンプレートに基づく設定ファイルの作成または更新
- [ ] 設定参照パターンの統一（${} 構文を使った参照）
- [ ] _target_ パスの適切な設定

### 参考
- eventモジュールのHydra設定ファイル構造を参考にしてください
- Hydraの公式ドキュメントに従った設定ファイル構成を目指します
